{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "crontabchart.serviceAccountName" . }}
  labels:
{{ include "crontabchart.labels" . | indent 4 }}
{{- end -}}
